# Generated by Django 5.1.1 on 2024-09-28 00:22

import django_resized.forms
import medicos.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='foto',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], db_column='medic_image', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[736, 736], upload_to=medicos.models.generar_nombre, verbose_name='Avatar'),
        ),
    ]
