# Generated by Django 5.1.1 on 2024-09-26 19:50

import django_resized.forms
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], db_column='profile_image', default='https://rnkqnkvcketqhptlupct.supabase.co/storage/v1/object/public/storage-medics/avatars/avatar-placeholder.png', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[736, 736], upload_to=usuarios.models.generar_nombre, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, default='no-email.1de31248b17e4dbeac5a2f365fa51af2@noemail.com', max_length=254, null=True, unique=True, verbose_name='Correo Electronico'),
        ),
    ]
