# Generated by Django 5.1.1 on 2024-09-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_usuario_avatar_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, default='no-email.7eab874b2e3844f2b18da2975792bbf0@noemail.com', max_length=254, null=True, unique=True, verbose_name='Correo Electronico'),
        ),
    ]
