# Generated by Django 5.1.1 on 2024-09-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, default='no-email.0a9fe9b6be41477e87a52a211757efb9@noemail.com', max_length=254, null=True, unique=True, verbose_name='Correo Electronico'),
        ),
    ]
