# Generated by Django 5.1.1 on 2024-10-29 19:19

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=40, unique=True, verbose_name='Genero')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualización')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='alergias',
            field=models.CharField(default=1, max_length=255, verbose_name='Alergias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='emergency_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(default=1, max_length=128, region=None, unique=True, verbose_name='Contacto de Emergencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='patologia',
            field=models.CharField(default=123, max_length=255, verbose_name='Patología'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='create_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, default='no-email.a2bc8cf464d34e698017ff625a6e07a5@noemail.com', max_length=254, null=True, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.genero', verbose_name='Genero'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sistolic', models.IntegerField(verbose_name='Sistólica')),
                ('diastolic', models.IntegerField(verbose_name='Diastólica')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
