# Generated by Django 5.1.1 on 2024-09-27 22:28

import examenes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=examenes.models.Examen.upload_to, verbose_name='Archivo'),
        ),
    ]
